apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: n8n
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: n8n
  policy:
    semver:
      range: ">=2.0.0 <3.0.0"
