apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
spec:
  secretName: n8n-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - n8n.staging.local
  privateKey:
    algorithm: ECDSA
    size: 256
