apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: change-me-generate-with-openssl-rand-hex-32
  N8N_HOST: n8n.CHANGE_ME.local
  N8N_PORT: "5678"
  N8N_PROTOCOL: https
