queueMode:
  enabled: false

database:
  type: postgresdb
  useExternal: true
  host: n8n-db-rw.CHANGE_ME_NAMESPACE.svc
  port: 5432
  database: n8n
  user: n8n
  passwordSecret:
    name: n8n-db-credentials
    key: password

redis:
  enabled: false

replicaCount: 1

persistence:
  enabled: false

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: n8n.CHANGE_ME.local
      paths:
        - path: /
          pathType: Prefix

webhook:
  enabled: true
  url: http://n8n.CHANGE_ME.local

config:
  timezone: Europe/Moscow
  extraEnv:
    - name: WEBHOOK_URL
      value: http://n8n.CHANGE_ME.local/
    - name: N8N_EDITOR_BASE_URL
      value: http://n8n.CHANGE_ME.local

secretRefs:
  existingSecret: n8n-secrets

resources:
  main:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
